### ISSUE TITLE
Filter / show retweets?

### ISSUE THREAD

**Issue by johneemac** [ssplugin/ss-twitter-feed#1]
Looks like an interesting plugin.

How would one go about showing / filtering by retweets?

**Comment by ssplugin** [comment]
What do you mean by filtering retweets? If you think about sorting / ordering retweet. if yes, we will update our plugin for filtering in next version.


Thank you very much.

**Comment by ssplugin** [comment]
@johneemac 
If you think exclude retweet, You should try to pass second parameter like:

`{% for tweet in craft.ssTwitterFeed.displayPost( '5', 'true' ) %}`
`{% endfor %}`
