### ISSUE TITLE
Tweets with Inline video not displayed

### ISSUE THREAD

**Issue by miro94** [ssplugin/ss-twitter-feed#10]
If the tweet contains an inline video, the whole tweet will not be shown in the timeline.
Example Tweet: https://twitter.com/zugwest/status/1164569825492066304?s=20

**Comment by ssplugin** [comment]
@miro94 
We have reviewed your given example. 
This is tweet like "Tweets and Replies". So when getting your timeline we have to exclude Replies so that this tweet does not show in the timeline.
We are working on a new version. In the new version, we will add this functionality.
