### ISSUE TITLE
Possible to get first image URL

### ISSUE THREAD

**Issue by mark-chief** [ssplugin/ss-twitter-feed#13]
Is it possible to grab an image src url that I can use in an image tag?

E.g:
`<img src="{{ tweets.image_url }}" />`

As you are not able to embed images using the `{{ images.url }}`

Thanks for your hard work.

**Comment by ssplugin** [comment]
If you want to add a single image in the feed then use 
`{% for tweet in craft.ssTwitterFeed.displayPost( '5' ) %}`
        `<img src="{{ tweet.image_url }}" >`
`{% endfor %}`

OR

`images` variable is array of images in each tweet. So you can be a loop through this variable Like below:

`{% for tweet in craft.ssTwitterFeed.displayPost( '5' ) %}`
      `{% for images in tweet.images %}`
        `<img src="{{ images.urll }}" />`
     `{% endfor %}`
`{% endfor %}`

**Comment by marcelvillerius** [comment]
Thank you for this great plugin!

I have two questions about the images tags:

1.  Is it possible to use image transforms? In my case it doesn't work:
```
{% for tweet in craft.ssTwitterFeed.displayPost( '5' ) %}
   <img src="{{ tweet.image_url('imageTransform') }}" >
{% endfor %}
```
2. The array of images from `images` gives an URL that isn't understand by the images tag. Is there something I do wrong:
```
{% for images in tweet.images %}
   <img src="{{ images.urll }}" />
{% endfor %}
```
->  `<img src="https://t.co/nQI51BoFtR">`

**Comment by ssplugin** [comment]
@marcelvillerius 

1. The first thing is image transformation functionality not supported our plugin. 
An alternative way to set image width and height:
`<img src="{{ tweet.image_url }}" width="10%" height="10%">`

2. `images` variable gives an image URL not an HTML tag because the user can set an HTML tag manually for a better frontend style.

We have accepted your suggestion and will add future plugin update.

Thanks you.

**Comment by marcelvillerius** [comment]
Thank you for your response!

I wasn't clear enough in my second question, sorry. When I use:
```
{% for images in tweet.images %}
   <img src="{{ images.url }}" />
{% endfor %}
```
It will give the URL of the tweet, not the URL of the image:

`{{ images.url }}  --> https://t.co/nQI51BoFtR`

Maybe I do something wrong, or the plugin asks the wrong item. Can you take a look at it?

Thank you

**Comment by ssplugin** [comment]
@marcelvillerius 

We have checked with your example.
So the `images` variable has multiple arrays elements. like` url`, `media_url` etc..

Now you should use `media_url` instead of `url`.

```
{% for images in tweet.images %}
   <img src="{{ images.media_url}}" />
{% endfor %}
```

**Comment by marcelvillerius** [comment]
Great, that works. Thank you very much!
