### ISSUE TITLE
Settings page times out on local dev

### ISSUE THREAD

**Issue by ZapaNOR** [ssplugin/ss-twitter-feed#15]
When trying to access the settings page from local dev I get this error:

`Abraham\TwitterOAuth\TwitterOAuthException`
From the file "vendor/abraham/twitteroauth/src/TwitterOAuth.php" line 551, called on by "Abraham\TwitterOAuth\TwitterOAuth::request('https://api.twitter.com/oauth/re...', 'POST', 'Authorization: OAuth oauth_versi...', [], ...)"

**Comment by ssplugin** [comment]
@Mathias-Syversen 
Can you recheck or try to access setting page?
Because we have just updated plugin and solved issue but still error occurs please explain in details.
You have to update this plugin after recheck. New plugin version is "1.0.5".
Happy to help you!!
