### ISSUE TITLE
Is it possible to add card previews?

### ISSUE THREAD

**Issue by knifejuggler** [ssplugin/ss-twitter-feed#16]
I saw this on Twitter's API pages and wondered if this could be implemented?
[https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/summary]

**Comment by ssplugin** [comment]
@knifejuggler 

> I saw this on Twitter's API pages and wondered if this could be implemented?

 No, This feature not implemented yet in our plugin. But we are working on that.
      But what you will expecting please explain more about so we will consider your requirement in 
      the our next version.

**Comment by knifejuggler** [comment]
Just the ability to have preview cards for links on the feed on my website, rather than just a plain link.
