### ISSUE TITLE
'tweet_date' parameter not working

### ISSUE THREAD

**Issue by dr-codswallop** [ssplugin/ss-twitter-feed#19]
Relating to [issue #9](https://github.com/ssplugin/ss-twitter-feed/issues/9) that may have been closed prematurely, the `tweet_date` parameter from the docs doesn't seem to be available.

```
{% for tweet in tweets %}
  {{tweet.tweet_date}}
{% endfor %}
```
`Key "tweet_date" for array with keys "name, screen_name, text, text_html, profile_image_url, url, image_url, images, retweet_count, favorite_count, created_at, retweet_link, favorite_link" does not exist.`

**Comment by andyharris** [comment]
Getting exactly the same problem as above, tweet_date not available - is there an update available to fix this?

**Comment by ssplugin** [comment]
@dr-codswallop @andyharris 

Install/update plugin version `1.0.7`.
The `tweet_date` variable has been added. Also solved issue regarding the composer 2 compabilities
