### ISSUE TITLE
tweet.image_url only work on some tweets

### ISSUE THREAD

**Issue by solutiondrop** [ssplugin/ss-twitter-feed#2]
Hi, 
Thanks for taking the time to create your plugin. I've set everything up and authorized the plugin. 

My issue is that when I use image_url to get images from the Tweets I only see 2 urls being pulled in out of what should be 7 image urls.

Here is the page in question. Right now it simply shows 10 tweets and their components using your plugin followed by a Twitter embed showing the same 10 tweets for comparing the two. 
https://www.williambryantlogan.com/twitter

Do you have any advise on how I might get the image urls for the Tweets that have images but aren't being display by the plugin?

**Comment by ssplugin** [comment]
Hello solutiondrop,
We have viewed site on the above provided link, but we have not able to see any plugin code on that page.
But show **Generic Error** on that page
Thanks...

**Comment by ssplugin** [comment]
Hello @solutiondrop ,
 We have added multiple images variable for retrieve multiple images. 
images variable is multidimensional array so you should retrieve like following example:
   ` {% for tweet in craft.ssTwitterFeed.displayPost( '5' ) %}`
         ` {% for images in tweet.images %}`
              `{{ images.url }}`
         ` {% endfor %}`	
     `{% endfor %}`

**You should install new version( 1.0.1 ) of our plugin**
