### ISSUE TITLE
Failed to instantiate component or class - New Install

### ISSUE THREAD

**Issue by mark-chief** [ssplugin/ss-twitter-feed#24]
I installed the plugin through the plugin store in craft 3.6.8 then clicked on the plugin settings icon.

`Failed to instantiate component or class "ssplugin\sstwitterfeed\assetbundles\sstwitterfeed\SsTwitterFeedAsset".`

Manually ran `composer update `to see if that would fix but no luck.

Attached error:
<img width="1834" alt="Screenshot 2021-03-04 at 10 47 22" src="https://user-images.githubusercontent.com/18699249/109952987-62a93000-7cd7-11eb-9364-58643fbf3329.png">

Thanks for any help in getting this working

**Comment by ssplugin** [comment]
@mark-chief 

We have investigated this issue. It has happened because the class name not found due to the PSR-4 standard. so we have updated plugin version `1.0.8`.
