### ISSUE TITLE
Getting redirect to "Page Not Found"

### ISSUE THREAD

**Issue by knynkwl** [ssplugin/ss-twitter-feed#29]
<img width="991" alt="Screen Shot 2021-09-29 at 2 40 22 PM" src="https://user-images.githubusercontent.com/4225771/135329166-1dddc208-66b0-4a71-913f-d4938b278d45.png">

This is the url that is being generated (i removed the keys and return uri for privacy)
http://www.systemseeders.com/twitterapp/ss-twitter-feed.php?return_uri=https://*******.com/admin/actions/ss-twitter-feed/oauth/callback&oauth_token=*********&oauth_verifier=*******

**Comment by ssplugin** [comment]
@knynkwl 

Actually, after being authorized from twitter the redirect event was not successful because of the server was denied.
We have investigated this issue and now fixed it.
