### ISSUE TITLE
Getting `Undefined property: stdClass::$retweeted_status`

### ISSUE THREAD

**Issue by phirefly** [ssplugin/ss-twitter-feed#3]
I'm getting this when dropping this into my app:

> PHP Notice – yii\base\ErrorException
Undefined property: stdClass::$retweeted_status

It's complaining here: https://github.com/ssplugin/ss-twitter-feed/blob/master/src/variables/SsTwitterFeedVariable.php#L63

I'm on Craft 3.0.4.1

Any thoughts?

**Comment by ssplugin** [comment]
We have checked this issue.

> I'm getting this when dropping this into my app:
> 
> > PHP Notice – yii\base\ErrorException
> > Undefined property: stdClass::$retweeted_status
> 
> It's complaining here: https://github.com/ssplugin/ss-twitter-feed/blob/master/src/variables/SsTwitterFeedVariable.php#L63
> 
> I'm on Craft 3.0.4.1
> 
> Any thoughts?

We have solved this errors in our new version 1.0.1. Now You should uninstall old plugin and install new one.

Thanks

**Comment by phirefly** [comment]
@ssplugin works like a charm!
