### ISSUE TITLE
Plugin doesn't really... work?

### ISSUE THREAD

**Issue by michaelpelletier** [ssplugin/ss-twitter-feed#30]
In addition to the other issue about the 404 on authenticating, this only returns two tweets no matter what you change the setting to, doesn't seem to refetch tweets when I make changes (eg: disabling fetching retweets), and doesn't seem to retrieve all of the information for even the two tweets it gets  (My second tweet is not even getting a "tweet_url")

**Comment by ssplugin** [comment]
@michaelpelletier 

1. This only returns two tweets no matter what you change the setting to:
>> We have checked with a different username and retrieved tweets. Default 10 tweet shows but describes in the documentation that passes parameter `craft.ssTwitterFeed.displayPost(50)` 
Please give your username so we can able to investigate more.


2. Doesn't seem to reflect tweets when I make changes (eg: disabling fetching retweets):
>> If you want to disable retweet then pass parameter `craft.ssTwitterFeed.displayPost(50, 'true')`


3. Doesn't seem to retrieve all of the information for even the two tweets it gets (My second tweet is not even getting a "tweet_url")
>> Actually `url` variable is used for getting tweet URL. But if you feel still an issue happen then give your Twitter username.
