### ISSUE TITLE
404 Error upon Twitter auth validation

### ISSUE THREAD

**Issue by johneemac** [ssplugin/ss-twitter-feed#4]
Hi,

Can't get this to authorise... Getting an 404 error when redirecting back to site from Twitter when getting token...

https://domain.com/actions/ss-twitter-feed/oauth/callback&oauth_token=REMOVEBwAAAAAA9e5BAAABaYIFtds&oauth_verifier=REMOVEvsO3YY22kFlKcBIOA2yU

**Comment by ssplugin** [comment]
@johneemac ,
We have installed this plugin in multiple craft installation, but this type of errors are not found.
Above link are not useful because oauth_token and verifier are not permanent.

- Some other causes like your site URL is not a proper because redirect URL is very important.
-Try to install other demo craft installation and check this error occurs or not.

Thanks

**Comment by frontedbe** [comment]
Experiencing the same issue like @johneemac ... What are the requirements for a proper redirect URL? I'm setting it up locally. [screenshot](https://cl.ly/8c09c014a723)

**Comment by johneemac** [comment]
@mdominguez are you using a non standard config set up?

I havn't had time to look into this but that could be it. I'll try and get some time over the next few days to explore what's wrong. Be handy in the @ssplugin guys could look into too.

**Comment by j2is** [comment]
I can't get it to authorise either I'm afraid, once it redirects it shows a 404. My site URL is proper, not sure what else to change

**Comment by kevadamson** [comment]
Can get this working locally, same error when trying to authorise.

**Comment by j2is** [comment]
This plugin does not work as Twitter have changed the way they authenticate, I suggest trying alternatives on the Craft Store

**Comment by terryupton** [comment]
Did anyone manage to get this working? I am getting the same 404 error...

**Comment by j2is** [comment]
No problem still exists, I think because Twitter requires app authorisation now, this plugin was written before that

**Comment by terryupton** [comment]
@j2is did you find another plugin or solution at all?

**Comment by j2is** [comment]
Twitter plugin by Dukt

**Comment by ssplugin** [comment]
> Experiencing the same issue like @johneemac ... What are the requirements for a proper redirect URL? I'm setting it up locally. [screenshot](https://cl.ly/8c09c014a723)

**Comment by ssplugin** [comment]
@johneemac @terryupton @mdominguez  @j2is @kevadamson 

We have look at this issue and test in our local and dev server. It is working fine.
Now, We need some more information from you so we can find what is an exact problem while redirect authorization?

So, you need to answer the following questions.
1. What is your craft version?
2. Craft site working in sub-directory? if yes then explain more.
3. What is your control panel URL ( cpTrigger )? Have you changed the CP URL in `config/general.php`?
4. Have you changed the base URL for the site? if yes then explain it.

Thank you for pointing us out.

**Comment by krupal-panchal** [comment]
@ssplugin @johneemac @j2is @terryupton 
I have tried this plugin and it is working good.
There is no issue of redirecting the 404 page after twitter authorization.

**Comment by ssplugin** [comment]
@johneemac @mdominguez @j2is @kevadamson 

We have again reviewed our plugin and but not getting the 404 error.
So, please describe more about the error.

1. What is redirect URL getting after authorized and back to your site?
    **Ex URL:**  `https://your-site-url/actions/ss-twitter-feed/oauth/callback&oauth_token=RdfsffsAABaYIFtds&oauth_verifier=fsdfMOVEvsO3YsdfsfsY22kFlKcBIOA2yU`

> (* if your `oauth_token` and `oauth_verifier` is wrong then '404' errors occur because this value is changed every time when you requested authorization.)

2. Have you changed the **cpTrigger** URL in the `config/general.php` file? If yes then explain.

**Comment by bennash** [comment]
Same issue, doesnt work.

**Comment by ssplugin** [comment]
> Same issue, doesn't work.

@bennash 
Can you explain about your issue or share errors with us?
Sometimes errors occurs because of wrong redirect URL.
