### ISSUE TITLE
urls not clickable in tweet

### ISSUE THREAD

**Issue by pixelman** [ssplugin/ss-twitter-feed#5]
Hi I am moving from EE to craft.
I got this issues with the links in the tweet.
can probably be fixed with some kind of |filter in craft?
I can paste the `{{ tweet.url }}` but its a separate thing. What I am looking for is that it automatically transforms the URLs inside the tweet.

**Current version**
![image](https://user-images.githubusercontent.com/221232/54782320-de129380-4c1e-11e9-935a-29bdadf098f9.png)

**should become like this** (was made in Expression Engine)
![image](https://user-images.githubusercontent.com/221232/54782182-883deb80-4c1e-11e9-9a9b-b4946d6ca35c.png)

many thanks

**Comment by ssplugin** [comment]
Good morning @pixelman ,

 **What I am looking for is that it automatically transforms the URLs inside the tweet.**
**>>**We will implement this type of functionality in our next update version.

Thanks for suggestion.

**Comment by ssplugin** [comment]
@pixelman 

We have  updated our plugin and added new variable which you can use with **raw** filter. It will automatically converts @mentions, #hashtags, URLs into links.

**{{ tweet.text_html | raw }}**

Please update the plugin to use above variable.

**Comment by pixelman** [comment]
WOW thank you this does the trick :)
![image](https://user-images.githubusercontent.com/221232/55006241-b4ba8480-4fdd-11e9-914a-48fa0b6d7c05.png)
