### ISSUE TITLE
Install error on PHP 7.0

### ISSUE THREAD

**Issue by alexjcollins** [ssplugin/ss-twitter-feed#7]
Getting a parse error when trying to use the plugin on an environment running php 7.0

```
ParseError

syntax error, unexpected 'const' (T_CONST), expecting variable (T_VARIABLE)
Caused by: ParseError

syntax error, unexpected 'const' (T_CONST), expecting variable (T_VARIABLE)

in site/vendor/ssplugin/ss-twitter-feed/src/SsTwitterFeed.php at line 67
```

`public` and `private` `const` are only available in php 7.1.
https://www.php.net/manual/en/language.oop5.constants.php

Is it possible to add support for 7.0?

**Comment by ssplugin** [comment]
@alexjcollins 
We have fixed php version compatibility, Now you have to update or reinstall the plugin.
Thanks.

**Comment by alexjcollins** [comment]
@ssplugin Thanks!
