### ISSUE TITLE
Trying to get property 'full_text' of non-object

### ISSUE THREAD

**Issue by danleecreates** [ssplugin/ss-twitter-feed#8]
Hi 

When setting up the plugin we get the following error... 

> PHP Notice – yii\base\ErrorException
> Trying to get property 'full_text' of non-object

![Screen Shot 2019-06-17 at 10 38 10](https://user-images.githubusercontent.com/7198242/59594694-3822d800-90ec-11e9-9a28-973bdbba1351.png)

Any idea what this could be realted to? I have added the Access token and Access token secret into the settings.

**Comment by ssplugin** [comment]
Hello @nearkingdom 

We have fixed this issue. 
Now you can download or update ss-twitter-feed plugin.

Thanks.
