### ISSUE TITLE
Date Format with twig  date

### ISSUE THREAD

**Issue by miro94** [ssplugin/ss-twitter-feed#9]
Thanks for creating this plugin.
It would be great to use the [twig date filter](https://twig.symfony.com/doc/2.x/filters/date.html) for formatting the created_at date.
As I can see, this is not possible yet.

**Comment by ssplugin** [comment]
Hello, @miro94 
We have added a new variable to display original date format which is given by twitter, Also you can be able to filter/formats date as you wish using the twig date filter.
`{{ tweet_date }}`
So now you can download or update ss-twitter-feed plugin.
Thanks.

**Comment by dr-codswallop** [comment]
The `tweet_date` array variable from the docs doesn't seem to be available.

```
{% for tweet in tweets %}
  {{tweet.tweet_date}}
{% endfor %}
```

`Key "tweet_date" for array with keys "name, screen_name, text, text_html, profile_image_url, url, image_url, images, retweet_count, favorite_count, created_at, retweet_link, favorite_link" does not exist.`
